version: '3.1'

services:
  springboot:
    image: aretimadhusudhan/spring-boot-mongo:latest
    restart: always # This will be ignored if we deploy in docker swarm
    environment:
    - MONGO_DB_HOSTNAME=mongo
    - MONGO_DB_USERNAME=madhu
    - MONGO_DB_PASSWORD=madhu123
    ports:
      - 8080:8080
    working_dir: /opt/app
    depends_on:
      - mongodb
    networks:
    - awsnetwork  
    deploy:  # This will be considered only in docker swarm.
      replicas: 2
      update_config:
        parallelism: 1
        delay: 20s
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5

  mongodb:
    image: mongo
    environment:
    - MONGO_INITDB_ROOT_USERNAME=madhu
    - MONGO_INITDB_ROOT_PASSWORD=madhu123
    volumes:
      - mongodb:/data/db
    restart: always
    networks:
    - awsnetwork
    
volumes:
  mongodb:
    external: false
    
networks:
  springappnetwork:
    external: false
